# Generated by Django 5.1.3 on 2024-11-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_entry_options_entry_is_public_alter_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
